name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login
      run: docker login -u  ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --tag loorky/sqlpackage:latest
      
    - name: Publish image
      run: docker push loorky/sqlpackage:latest
